name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
  - type: input
    id: version
    attributes:
      label: Version
      description: Chat Guard version (from package.json) and Node.js version
      placeholder: e.g., 1.3.3, Node 18.x
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the problem and what you expected to happen
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the behavior
      placeholder: 1) ..., 2) ..., 3) ...
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste logs or screenshots
      render: shell
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Local
        - Docker
        - Heroku
        - Other
  - type: input
    id: guild-size
    attributes:
      label: Approximate guild size
      placeholder: e.g., 350 members
